productos_list:
  - titulo: "Heladera Exhibidora Vertical 420 lts"
    categoria: "Línea de Frío"
    img_principal: "assets/images/frio/heladera-exhibidora-vertical-420-lts.png"
    badge_texto: "DESTACADO"
    wa_link: "https://wa.me/5493644177499"
  - titulo: "Freezer Horizontal Gafa"
    categoria: "Línea de Frío"
    img_principal: "assets/images/frio/freezer-horizontal-gafa.png"
    badge_texto: "NUEVO"
    wa_link: "https://wa.me/5493644177499"
  - titulo: "Spiedo 24 Pollos"
    categoria: "Gastronomía"
    img_principal: "assets/images/gastronomia/spiedo-calabro-24-pollos.png"
    badge_texto: "DESTACADO"
    wa_link: "https://wa.me/5493644177499"
