productos_list:
  - titulo: "Freidora Automática"
    categoria: "Sistemas de Pesaje"
    img_principal: "assets/images/gastronomia/freidora-automatica.jpeg"
    wa_link: "https://wa.me/5493644177499"
  - titulo: "Sierra Chica"
    categoria: "Línea Carnicería"
    img_principal: "assets/images/carniceria/sierrachica1.jpeg"
    wa_link: "https://wa.me/5493644177499"
  - titulo: "Sierra Grande 1"
    categoria: "Línea Carnicería"
    img_principal: "assets/images/carniceria/sierragrande1.jpeg"
    wa_link: "https://wa.me/5493644177499"
  - titulo: "Balanza Systel Clipse"
    categoria: "Sistemas de Pesaje"
    img_principal: "assets/images/sistemadepesaje/balanza-systel-clipse.webp"
    wa_link: "https://wa.me/5493644177499"
  - titulo: "Sobadora de Mesa 400mm"
    categoria: "Línea Panadería"
    img_principal: "assets/images/panaderia/liviana/liviana1.webp"
    wa_link: "https://wa.me/5493644177499"
  - titulo: "Caramelera 16 Div."
    categoria: "Exhibidores"
    img_principal: "assets/images/exhibidores/caramelera-16div.jpeg"
    wa_link: "https://wa.me/5493644177499"
