productos_list:
  - titulo: Spiedo 12 Rollos Calabro
    categoria: Gastronomía
    img_principal: assets/images/gastronomia/spiedo-calabro-12-pollos.png
    badge_texto: ""
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa el Spiedo de 12
      rollos Calabro
  - titulo: Spiedo 24 Rollos Calabro
    categoria: Gastronomía
    img_principal: assets/images/gastronomia/spiedo-calabro-24-pollos.png
    badge_texto: ""
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa el Spiedo de 24
      rollos Calabro
  - titulo: Cocina Industrial Pesada
    categoria: Gastronomía
    img_principal: assets/images/gastronomia/cocinaindustrial1.jpeg
    badge_texto: PRODUCTO DESTACADO
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Cocina Industrial
      Pesada
  - titulo: Cocina Semi-Industrial
    categoria: Gastronomía
    img_principal: assets/images/gastronomia/cocina-semi-industriales.jpeg
    badge_texto: ""
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Cocina
      Semi-Industrial
  - titulo: Freidora Automática
    categoria: Gastronomía
    img_principal: assets/images/gastronomia/freidora1.jpeg
    badge_texto: ""
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Freidora
productos_frio_list:
  - titulo: Conservadora para helados FAM 12 Tachos
    img_principal: assets/images/frio/conservadora-para-helados-12tachos.png
    wa_link: https://wa.me/5493644177499?text=Hola Nestor! Consulto por la FAM de 12
      tachos
    categoria: Frío
    badge_texto: PRODUCTO DESTACADO
  - titulo: Conservadora para helados FAM 16 Tachos
    img_principal: assets/images/frio/conservadora-para-helados-16-tachos-foto1.webp
    wa_link: https://wa.me/5493644177499?text=Hola Nestor! Consulto por la FAM de 16
      tachos
    categoria: Frío
  - titulo: Conservadora para helados FAM 18 Tachos
    img_principal: assets/images/frio/conservadora-para-helados-18-tachos-foto1.webp
    wa_link: https://wa.me/5493644177499?text=Hola Nestor! Consulto por la FAM de 18
      tachos
    categoria: Frío
  - titulo: Conservadora para helados FAM 22 Tachos
    img_principal: assets/images/frio/conservadora-para-helados-22-tachos-foto1.webp
    wa_link: https://wa.me/5493644177499?text=Hola Nestor! Consulto por la FAM de 22
      tachos
    categoria: Frío
  - titulo: Heladera Carnicera (Ganchera)
    img_principal: assets/images/frio/heladera-carnicera.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Heladera Carnicera
    categoria: Frío
    badge_texto: miqueasvico
  - titulo: Mini Cámara Frigorífica
    img_principal: assets/images/frio/mini-camaras.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa consultar el stock
      de la Mini Cámara
    categoria: Frío
  - titulo: Heladera Exhibidora
    img_principal: assets/images/frio/heladera-vitrina1.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Quiero consultar stock de
      la Heladera Exhibidora Vertical
    categoria: Frío
  - titulo: Heladera Exhibidora Doble Puerta
    img_principal: assets/images/frio/heladera-vitrina2.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Quiero consultar stock de
      la Heladera Exhibidora Doble Puerta
    categoria: Frío
  - titulo: Heladera Exhibidora 370 Lts
    img_principal: assets/images/frio/heladera-exhibidora-vertical1.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Exhibidora de 370 Lts
    categoria: Frío
  - titulo: Heladera Exhibidora 470 Lts
    img_principal: assets/images/frio/heladera-exhibidora-vertical2.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Exhibidora de 470 Lts
    categoria: Frío
productos_pesaje_list: []
productos_carniceria_list: []
productos_panaderia_list: []
productos_exhibidores_list: []
