productos_list:
  - titulo: Spiedo 12 Pollos Calabro
    categoria: Gastronomía
    img_principal: assets/images/gastronomia/spiedo-calabro-12-pollos.png
    badge_texto: ""
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa el Spiedo de 12
      pollos Calabro
  - titulo: Spiedo 24 Pollos Calabro
    categoria: Gastronomía
    img_principal: assets/images/gastronomia/spiedo-calabro-24-pollos.png
    badge_texto: ""
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa el Spiedo de 24
      pollos Calabro
  - titulo: Cocina Industrial Calabro 4 hornallas
    categoria: Gastronomía
    img_principal: assets/images/productos/img_0132.jpg
    badge_texto: ""
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Cocina Industrial
      Pesada
  - titulo: Cocina Industrial Calabro 6 hornallas
    categoria: Gastronomía
    img_principal: assets/images/productos/img_0294.jpg
    badge_texto: ""
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Cocina Industrial
  - categoria: Gastronomía
    titulo: Cocina Morelli con plancha
    img_principal: assets/images/productos/img_0298-2.jpg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Cocina Industrial
  - categoria: Gastronomía
    titulo: Cocina Semi-Industrial
    img_principal: assets/images/productos/img_0295.jpg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Cocina Industrial
  - titulo: Freidoras de 15lts y 35 lts
    categoria: Gastronomía
    img_principal: assets/images/productos/img_0293.jpg
    badge_texto: ""
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Freidora
  - categoria: Gastronomía
    titulo: Cortadoras de fiambres calibre 300
    img_principal: assets/images/productos/whatsapp-image-2026-01-26-at-7.19.33-pm.jpeg
    wa_link: https://wa.me/5493644177499?
  - categoria: Gastronomía
    titulo: Cortadoras de fiambres calibre 330
    img_principal: assets/images/productos/whatsapp-image-2026-01-26-at-7.19.34-pm.jpeg
    wa_link: https://wa.me/5493644177499?
  - categoria: Gastronomía
    titulo: Carlitera Simple
    img_principal: assets/images/productos/carliterasimple.png
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Carlitera Simple
  - categoria: Gastronomía
    titulo: Carlitera Doble
    img_principal: assets/images/productos/carliteradoble.png
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Carlitera Doble
  - categoria: Gastronomía
    titulo: Lomitera Simple
    img_principal: assets/images/productos/lomitera-simple.png
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Lomitera Simple
  - categoria: Gastronomía
    titulo: Lomitera Doble
    img_principal: assets/images/productos/lomitera-doble.png
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Lomitera Doble
productos_frio_list:
  - titulo: Conservadora para helados FAM 12 Tachos
    img_principal: assets/images/frio/conservadora-para-helados-12tachos.png
    wa_link: https://wa.me/5493644177499?text=Hola Nestor! Consulto por la FAM de 12
      tachos
    categoria: Frío
    badge_texto: ""
  - titulo: Conservadora para helados FAM 16 Tachos
    img_principal: assets/images/frio/conservadora-para-helados-16-tachos-foto1.webp
    wa_link: https://wa.me/5493644177499?text=Hola Nestor! Consulto por la FAM de 16
      tachos
    categoria: Frío
  - titulo: Conservadora para helados FAM 18 Tachos
    img_principal: assets/images/frio/conservadora-para-helados-18-tachos-foto1.webp
    wa_link: https://wa.me/5493644177499?text=Hola Nestor! Consulto por la FAM de 18
      tachos
    categoria: Frío
  - titulo: Conservadora para helados FAM 22 Tachos
    img_principal: assets/images/frio/conservadora-para-helados-22-tachos-foto1.webp
    wa_link: https://wa.me/5493644177499?text=Hola Nestor! Consulto por la FAM de 22
      tachos
    categoria: Frío
  - titulo: "Heladera Carnicera "
    img_principal: assets/images/productos/img_0134.jpg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Heladera Carnicera
    categoria: Frío
  - titulo: Mini Cámara Frigorífica
    img_principal: assets/images/productos/img_0285.jpg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa consultar el stock
      de la Mini Cámara
    categoria: Frío
  - titulo: Heladera Vitrina Chica
    img_principal: assets/images/productos/img_0282.jpg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Quiero consultar stock de
      la Heladera Vitrina Chica
    categoria: Frío
  - titulo: Heladera Vitrina 2 metros, 2,5 metros y 3 metros.
    img_principal: assets/images/productos/img_0280.jpg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Quiero consultar stock de
      la Heladera Exhibidora Doble Puerta
    categoria: Frío
  - titulo: Heladera Exhibidora 370 Lts
    img_principal: assets/images/productos/img_0142-2.jpg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Exhibidora de 370 Lts
    categoria: Frío
  - titulo: Heladera Exhibidora 470 Lts
    img_principal: assets/images/productos/img_0143-2.jpg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Exhibidora de 470 Lts
    categoria: Frío
  - categoria: Frío
    titulo: Heladera Exhibidora 980 Lts
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Exhibidora de 980 Lts
    img_principal: assets/images/productos/img_0145.jpg
  - categoria: Frío
    titulo: Pozo de frío de 1200 lts
    img_principal: assets/images/productos/d_nq_np_2x_967077-mla93531832476_102025-f.webp
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock del Pozo
      de frío de 1200 lts
  - categoria: Frío
    img_principal: assets/images/productos/whatsapp-image-2026-01-26-at-6.59.35-pm.jpeg
    titulo: Heladera mostrador vidrio curvo en 2 y 2,40 mts
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Heladera mostrador vidrio curvo
  - categoria: Frío
    titulo: Batea carnicera vidrio recto de 1,20  1,90  2  y 2,40 mts
    img_principal: assets/images/productos/batea-carnicera.jfif
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Batea carnicera vidrio recto
  - categoria: Frío
    titulo: Góndola de lactera de 1,30 mts
    img_principal: assets/images/productos/góndola-de-lactera-de-1-30-mts.png
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Góndola de lactera
  - categoria: Frío
    titulo: Heladera conservadora de hielo capacidad 90 bolsitas
    img_principal: assets/images/productos/whatsapp-image-2026-01-26-at-7.00.42-pm1.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Heladera conservadora de hielo
  - categoria: Frío
    titulo: Batea carnicera vidrio curvo 2 y  240 mts
    img_principal: assets/images/productos/0205000083-afed22a00f3c4a91bc17202052540242-1024-1024.webp
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Batea carnicera vidrio curvo
  - categoria: Frío
    titulo: Heladera vertical de 3 puertas 1200 lts
    img_principal: assets/images/productos/whatsapp-image-2026-01-26-at-7.00.44-pm.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Heladera vertical de 3 puertas
    badge_texto: ""
  - categoria: Frío
    titulo: Freezer Inelro 350 y 550 lts tapa ciega
    img_principal: assets/images/productos/sin-título.png
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock del
      Freezer Inelro
  - categoria: Frío
    titulo: Heladeras verticales inelro de 400 lts y 470 lts
    img_principal: assets/images/productos/d_nq_np_867047-mla99882199299_112025-o.webp
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Heladeras verticales Inelro
  - categoria: Frío
    titulo: Heladera vertical Inelro de 980 lts
    img_principal: assets/images/productos/sin-título2.png
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Heladeras verticales Inelro
  - categoria: Frío
    titulo: Heladera Carnicera
    img_principal: assets/images/productos/sin-título3.png
    wa_link: https://wa.me/5493644177499?text=Hola Néstor! Consulto stock de la
      Heladera Carnicera
productos_pesaje_list:
  - titulo: Balanza Systel Clipse
    img_principal: assets/images/sistemadepesaje/balanza-systel-clipse.webp
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Balanza Systel
    categoria: Pesaje
    badge_texto: PRODUCTO DESTACADO
  - titulo: Balanza Comercial Systel Cuora Max - 30kg
    img_principal: assets/images/sistemadepesaje/balanza comercial systel cuora max.webp
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Balanza Cuora Max
    categoria: Pesaje
  - titulo: Balanza Systel Croma - 31kg
    img_principal: assets/images/sistemadepesaje/Balanza comercial digital Systel Croma.webp
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Balanza Croma
    categoria: Pesaje
  - titulo: Balanza Aura Eco Kretz
    img_principal: assets/images/sistemadepesaje/Balanza Aura Eco.webp
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Balanza Aura Eco
    categoria: Pesaje
  - titulo: Balanza Novel Eco Kretz
    img_principal: assets/images/sistemadepesaje/Balanza Novel Eco.webp
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Balanza Novel Eco
    categoria: Pesaje
  - titulo: Balanza Kretz Report LT 30 Kg
    img_principal: assets/images/sistemadepesaje/balanza comercial digital kretz report.webp
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Balanza Kretz Report
    categoria: Pesaje
productos_carniceria_list:
  - titulo: Sierra Chica
    subcategoria: Línea Liviana
    img_principal: assets/images/productos/img_0130.jpg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Sierra Carnicera
      de Mesa
    categoria: Carnicería
    badge_texto: PRODUCTO DESTACADO
  - titulo: Embutidora
    subcategoria: Línea Liviana
    img_principal: assets/images/carniceria/embutidora1.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Embutidora
    categoria: Carnicería
  - titulo: Picadora de Carne
    subcategoria: Línea Liviana
    img_principal: assets/images/carniceria/picadora-de-carne-1.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Picadora de Carne
    categoria: Carnicería
  - titulo: Picadora de Carne 2
    subcategoria: Línea Liviana
    img_principal: assets/images/carniceria/picadora-de-carne-2.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Picadora de Carne
    categoria: Carnicería
  - titulo: Sierra Grande 1
    subcategoria: Línea Pesada
    img_principal: assets/images/carniceria/sierragrande1.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Sierra Carnicera
      1.5 HP
    categoria: Carnicería
  - titulo: Sierra Grande 2
    subcategoria: Línea Pesada
    img_principal: assets/images/carniceria/sierragrande2.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Sierra Carnicera
      2.0 HP
    categoria: Carnicería
productos_panaderia_list:
  - titulo: Sobadora de Mesa 400mm
    subcategoria: Línea Liviana
    img_principal: assets/images/productos/img_0283.jpg
    wa_link: https://wa.me/5493644177499?text=Consulto por Sobadora
    categoria: Panadería
    badge_texto: PRODUCTO DESTACADO
  - titulo: Amasadora 10 Kg Estándar
    subcategoria: Línea Liviana
    img_principal: assets/images/productos/img_0289.jpg
    wa_link: https://wa.me/5493644177499?text=Consulto por Amasadora 10kg
    categoria: Panadería
  - titulo: Amasadora 50 Kg Reforzada
    subcategoria: Línea Pesada
    img_principal: assets/images/productos/img_0291.jpg
    wa_link: https://wa.me/5493644177499?text=Consulto por Amasadora 50kg
    categoria: Panadería
  - titulo: Sobadora de Pie 500mm Profesional
    subcategoria: Línea Pesada
    img_principal: assets/images/productos/img_0287.jpg
    wa_link: https://wa.me/5493644177499?text=Consulto por Sobadora de Pie
    categoria: Panadería
  - titulo: Trinchadora Pan
    subcategoria: Línea Pesada
    img_principal: assets/images/panaderia/pesada/pesada3.jpeg
    wa_link: https://wa.me/5493644177499?text=Consulto por trinchadora
    categoria: Panadería
  - titulo: Horno Convector Dynam
    subcategoria: Línea Pesada
    img_principal: assets/images/productos/img_0141.jpg
    wa_link: "https://wa.me/5493644177499?text=Consulto por Horno Convector "
    categoria: Panadería
  - categoria: Panadería
    titulo: Horno Convector Morelli
    img_principal: assets/images/productos/img_0140.jpg
    wa_link: "https://wa.me/5493644177499?text=Consulto por Horno Convector "
  - titulo: Horno Convector Brafh 5 bandejas
    subcategoria: Línea Pesada
    img_principal: assets/images/productos/img_0137.jpg
    wa_link: https://wa.me/5493644177499?text=Consulto por Horno Convector Industrial
    categoria: Panadería
  - titulo: Horno Convector Brafh 10 bandejas
    subcategoria: Línea Pesada
    img_principal: assets/images/productos/img_0139.jpg
    wa_link: https://wa.me/5493644177499?text=Consulto por Horno Convector Industrial
    categoria: Panadería
productos_exhibidores_list:
  - titulo: Caramelera 16 Div.
    img_principal: assets/images/exhibidores/caramelera-16div.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Caramelera 16
      divisiones
    categoria: Exhibidores
  - titulo: Mostrador de Vidrio
    img_principal: assets/images/productos/mostrador-de-vidrio.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa el Mostrador de Vidrio
    descripcion_modal: Disponible en medidas de 1.00m, 1.50m y 2.00m. Podés elegir
      mesada de vidrio o laminada según tu necesidad.
    categoria: Exhibidores
  - titulo: Mostrador Facturero
    img_principal: assets/images/exhibidores/mostrador-facturero.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa el Mostrador Facturero
    categoria: Exhibidores
    badge_texto: 3, 5 y 6 bandejas
  - titulo: Vitrina Platos Calientes
    img_principal: assets/images/exhibidores/vitrina-para-platos.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Vitrina para
      platos calientes
    categoria: Exhibidores
    badge_texto: PRODUCTO DESTACADO
  - titulo: Panera 2 Div.
    img_principal: assets/images/exhibidores/panera-2divisiones.jpeg
    wa_link: https://wa.me/5493644177499?text=Hola! Me interesa la Panera de 2
      divisiones
    categoria: Exhibidores
